# In-memory H2 database
spring.datasource.url=jdbc:h2:mem:gym-crm;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop

# Disable Kafka
spring.kafka.enabled=false
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

# Disable Eureka
eureka.client.enabled=false
spring.cloud.discovery.enabled=false

# JWT
security.jwt.secret=6cphIzZx0mXxVauGgSNM2WvPmy_2EDu7Bl70ZHJppH4
security.jwt.lifetime=30m

# Actuator
management.endpoint.health.show-details=always
management.endpoints.web.exposure.include=*

# Disable file appender - log to stdout only
logging.file.name=
logging.pattern.console=%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr([%15.15t]){faint} %clr([TxnId: %X{transactionId:-NO_TXN}]){cyan} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
